#/bin/sh
python data_prepare.py;
python data_sa.py C;
python data_sa.py R;
python data_prepare.py;
python data_sa.py C;
python data_sa.py R;
python data_prepare.py;
python data_sa.py C;
python data_sa.py R;
python data_prepare.py;
python data_sa.py C;
python data_sa.py R;
python data_prepare.py;
python data_sa.py C;
python data_sa.py R;
python data_prepare.py;
python data_sa.py C;
python data_sa.py R;
python data_prepare.py;
python data_sa.py C;
python data_sa.py R;
python data_prepare.py;
python data_sa.py C;
python data_sa.py R;
python data_prepare.py;
python data_sa.py C;
python data_sa.py R;
python data_prepare.py;
python data_sa.py C;
python data_sa.py R;